language: node_js
node_js:
  - "0.10"

notifications:
  email: false

branches:
  only:
    - gh-pages
before_install: npm install -g codeclimate-test-reporter
after_sucess: CODECLIMATE_REPO_TOKEN=1485c05d5746f9e444c8de7c99ccef4261349bf8f337ddbca74da34e42aba0d4 codeclimate-test-reporter < coverage/lcov.info

